# Generated by Django 6.0.1 on 2026-01-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
